### PR TITLE
Add Turkish Translate

### PR DESCRIPTION
**Pull request by CanerKaraca23**

### CODE REVIEW

**Comment by acidicoala** [comment]
Thank you!

**Comment by acidicoala** [comment]
P.S. The `logging`  field means writing log file, not signing in. According to google translate it should be something like "seyir defterine yazmak". I will use "Günlük dosyasını yazmak" to make it consistent with other translated words.

**Comment by CanerKaraca23** [comment]
> P.S. The `logging` field means writing log file, not signing in. According to google translate it should be something like "seyir defterine yazmak". I will use "Günlük dosyasını yazmak" to make it consistent with other translated words.

You can change as "Kayıt ediliyor". Thanks for clarifying.

**Comment by hyesmo** [comment]
"loglamak" is a valid word in programming community and it means to log/logging. there were some localization problems, and an inconsistency. fixed them on my pr. @CanerKaraca23 you can check it out too. #8

**Comment by CanerKaraca23** [comment]
> "loglamak" is a valid word in programming community and it means to log/logging. there were some localization problems, and an inconsistency. fixed them on my pr. @CanerKaraca23 you can check it out too. #8

Will check, thanks for corrections.

**Pull request merged**
